version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: "db"
            POSTGRES_HOST_AUTH_METHOD: "trust"

    
    web:
        build: .
        volumes:
            - .:/user/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0
        ports:
            - "8000:8000"