FROM python:3
COPY . /user/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0
WORKDIR /user/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0
#RUN pip install -r requirements.txt
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]




#COPY . /usr/src/app
#WORKDIR /usr/src/app