# Generated by Django 4.1 on 2022-10-22 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_user_profile_picture_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
