# Generated by Django 4.1 on 2022-10-24 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_rename_follower_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='another_user',
            field=models.ManyToManyField(null=True, related_name='another_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
