# Generated by Django 4.1 on 2022-10-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_remove_follow_followers_remove_follow_following_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
