# Generated by Django 4.1 on 2022-10-27 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_remove_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ManyToManyField(blank=True, null=True, related_name='follower_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='following_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
