# Generated by Django 4.1 on 2022-10-12 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid_alter_listing_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
        migrations.AddField(
            model_name='listing',
            name='highestBid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='highestBidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highestBidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='startingPrice',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
