# Generated by Django 4.1.4 on 2023-01-18 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cite', '0010_alter_project_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='articles',
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagefrom', models.IntegerField(null=True)),
                ('pageto', models.IntegerField(null=True)),
                ('article', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='cite.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='citations',
            field=models.ManyToManyField(blank=True, related_name='citations', to='cite.citation'),
        ),
    ]
