# Generated by Django 4.1 on 2023-04-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmi', '0004_manuscript_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manuscript',
            old_name='day',
            new_name='yearfrom',
        ),
        migrations.RenameField(
            model_name='manuscript',
            old_name='month',
            new_name='yearto',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='year',
        ),
    ]
