# Generated by Django 4.1 on 2023-04-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmi', '0005_rename_day_manuscript_yearfrom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscript',
            name='image',
        ),
        migrations.AddField(
            model_name='manuscript',
            name='imageurl',
            field=models.TextField(blank=True),
        ),
    ]
