# Generated by Django 4.1 on 2023-04-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmi', '0007_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='user',
        ),
    ]
