# Generated by Django 4.1 on 2023-04-25 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wmi', '0008_remove_email_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='manuscriptid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='manuscriptid', to='wmi.manuscript'),
            preserve_default=False,
        ),
    ]
