# Generated by Django 4.1 on 2023-04-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmi', '0011_remove_email_recipient_email_recipients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='recipients',
        ),
    ]
