# Generated by Django 4.1 on 2023-04-25 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wmi', '0013_email_recipients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='recipients',
        ),
        migrations.AddField(
            model_name='email',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emails_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
