# Generated by Django 4.1 on 2023-04-25 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmi', '0014_remove_email_recipients_email_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='manuscriptid',
            new_name='manuscript',
        ),
    ]
