# Generated by Django 4.1 on 2023-05-17 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wmi', '0015_rename_manuscriptid_email_manuscript'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.ManyToManyField(related_name='conversation_emails', to='wmi.email')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversation_manuscriptid', to='wmi.manuscript')),
                ('participants', models.ManyToManyField(max_length=2, related_name='conversation_participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
