# Generated by Django 4.1 on 2023-05-17 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmi', '0017_remove_conversation_emails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='participants',
        ),
        migrations.AddField(
            model_name='conversation',
            name='emails',
            field=models.ManyToManyField(related_name='conversation_emails', to='wmi.email'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversation_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
