# Generated by Django 4.1 on 2023-05-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmi', '0019_conversation_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='email',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='email',
            name='read',
        ),
        migrations.RemoveField(
            model_name='email',
            name='subject',
        ),
    ]
