# Generated by Django 4.1 on 2022-11-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
