# Generated by Django 4.1 on 2022-10-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_user_followers_remove_user_following_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follower',
        ),
    ]
