# Generated by Django 4.1 on 2022-10-22 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_profile_profile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
