# Generated by Django 4.1 on 2022-10-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_alter_profile_bio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follower',
            new_name='Follow',
        ),
    ]
