# Generated by Django 4.1 on 2022-10-27 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_alter_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ManyToManyField(blank=True, null=True, related_name='follower_users', to='network.follow')),
                ('following', models.ManyToManyField(blank=True, null=True, related_name='following_users', to='network.follow')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
