# Generated by Django 4.1 on 2022-10-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_alter_profile_profile_owner_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
