# Generated by Django 4.1.4 on 2023-01-13 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cite', '0004_article_date_alter_article_title_alter_article_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='day',
        ),
        migrations.RemoveField(
            model_name='article',
            name='month',
        ),
        migrations.RemoveField(
            model_name='article',
            name='year',
        ),
    ]
