# Generated by Django 4.1.4 on 2023-01-13 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cite', '0005_remove_article_day_remove_article_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='journal',
        ),
    ]
