# Generated by Django 4.1.4 on 2023-01-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cite', '0006_remove_article_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
        migrations.AddField(
            model_name='article',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
