# Generated by Django 4.1.4 on 2023-01-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cite', '0009_project_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='articles',
            field=models.ManyToManyField(null=True, related_name='emails_received', to='cite.article'),
        ),
    ]
